[package]
name = "notifyhealth"
version = "0.1.0"
edition = "2021"
authors = ["Giovanni Bassi <giggio@giggio.net>"]

[dependencies]
bollard = "0.11.1"
clap = { version = "3.1.2", features = ["derive"] }
clap-verbosity-flag = "1.0.0"
env_logger = "0.9.0"
futures-util = "0.3.21"
tokio = { version = "1.17.0", features = ["full"] }

[dev-dependencies]
pretty_assertions = "1.1.0"
