[package]
name = "notifyhealth"
version = "0.1.0"
edition = "2021"
authors = ["Giovanni Bassi <giggio@giggio.net>"]

[profile.release]
strip = true
lto = true

[dependencies]
async-trait = "^0.1"
bollard = "^0.11"
clap = { version = "^3.1", features = ["derive"] }
clap-verbosity-flag = "^1.0"
env_logger = "^0.9"
futures = "^0.3"
futures-util = "^0.3"
itertools = "^0.10"
log = "^0.4"
serde = "^1.0"
tokio = { version = "^1.17", features = ["full"] }

[dev-dependencies]
mockall = "^0.11"
pretty_assertions = "^1.1"
